name: Vitest
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to latest
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install
        run: pnpm i

      - name: Install Playwright Dependencies
        run: pnpm exec playwright install chromium --with-deps

      - name: Test
        run: pnpm vitest run --coverage
